### ISSUE TITLE
Investigate facebook integration

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/nazareth-events#171]
Ie from data entry and to data entry

**Comment by Karyum** [comment]
So after an hour researching Facebook's Graph API on how to use it and what do i need to access it i got to a dead end a bit for the following 2 reasons:
 
- There is no way to create events on Facebook through the Graph API for some reason they [removed it in the new version](https://developers.facebook.com/docs/graph-api/reference/v2.0/event#publish).

- I can't get user's or page's events even if the user has authenticated themselves, i need to submit a request to Facebook of my app that im building so that i can even ask for user's events, but even before submitting the request i need to fill some requirements they asked for, for example 1024x1024 app icon and more fairly easy ones but enough to stop from continuing.

I'm going to submit a test app to Facebook just to see how long the procedure would take and how easy is to set it up. i'll follow up with result soon

**Comment by des-des** [comment]
Nope we are not, we are executing an *already* compiled template
Note the difference between compiling and executing: http://handlebarsjs.com/

**Comment by des-des** [comment]
@Karyum :+1:

**Comment by Karyum** [comment]
They are currently asking me to send a video/screencast of how am i going to use the events that im going to get from the user in my app, also for a reason why do i need the events and `instructions for how to reproduce this permission` ? which i have no idea what they mean by that :sweat_smile:  
just a reminder they are asking all of this just to be allowed to ask the user for permission to get his/her events.

should i go on with @des-des ?

**Comment by des-des** [comment]
@Karyum thanks for the update (loving the gh updates)!

I think for now we can move this into backlog

**Comment by des-des** [comment]
Or, consider initial investigation done
