### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by JWLD** [foundersandcoders/nazareth-events#63]
- [x] Language select in top menu bar - `English` or `English and Arabic`
- [x] Update events form to allow Arabic for `name`, `description`
- [x] Update places form to allow Arabic for `name`

**Comment by Karyum** [comment]
Make a file which has 2 objects english and arabic.
English object has english keys which their values are english words
Arabic object has english keys with arabic words.
- [ ] make the english object
- [ ] translate to arabic and add it to the arabic project 
- [ ] implement it in the hbs files

**Comment by mattlub** [comment]
Hey- this is not exactly the 'multi-language support' which was discussed with Silke initially- when I get to a computer I can write in more detail- but basically it would be on the list page, the ability to select between seeing only English events (tourists) or events in English and Arabic (locals)

**Comment by mattlub** [comment]
And I guess the add event form should have the option to add event information in Arabic

**Comment by JWLD** [comment]
Ok cool, yea some more detail would be good, cheers Lubes

**Comment by mattlub** [comment]
ok- what I said above was pretty much it- @SilkeLiwan  proposed a **language select option** (I assume in the top menu bar, although this wasn't finalised) which would affect which events you saw. She wanted the options to be (at the most simple) either 'English' or 'English and Arabic'.

Also you would have to **add fields to the add-event form**  to give the option to enter the event information (name, description) in Arabic as well as/instead of English.

---

We did not plan to translate static text on the site to arabic, as it was assumed that almost all the users would have at least a basic grasp of english.

You would also need to think about/discuss what should be displayed if the event has information in both English and Arabic.

**Comment by Karyum** [comment]
@JWLD @mattlub so do you think it's a good idea to just add more inputs to the add event form.
cause imagine someone wants to add and event in english and arabic and wants to add a new place, thats just loads of inputs to go through im guessing it's bad UX

**Comment by mattlub** [comment]
@Karyum I think for the event fields, yes add the 2 new input fields. I'm not sure what the best way to present it is, look [here](https://nazareth-open-tourism-platform.herokuapp.com/register) for an example of how we did it.

In my opinion it is not a bad thing to add some explanatory text in the middle of the form if it's not possible to lay things out in a way which makes it obvious which fields are required.

Maybe you can ask Noga's advice about this page.

**Comment by mattlub** [comment]
@Karyum for the places fields, I think it needs a bit of a rethink. Remember that only the name is required for a new place, maybe we should remove and reorder some of the fields.

For example, the 'location' field (the first field) expects coordinates but there is no way you can expect someone to know the coordinates of a location.

**Comment by JWLD** [comment]
@mattlub If the user selects 'English and Arabic' and an event has both language options filled out, which should render? Seems to make more sense to me to have either English or Arabic as options, not both at once.

**Comment by Karyum** [comment]
@JWLD why do we need to the opening hours to be translated?
 > - [ ] Update places form to allow Arabic for `name`, `description`, `address`, `opening hours`

**Comment by mattlub** [comment]
> an event has both language options filled out, which should render?

- on the home page, I'm not sure which title should render, but I would say this will be easy to change if we decide we get it wrong.
- on the details page, it could be good to render the description in both languages if they're both present (if on the arabic and english setting)

> Does Silke definitely want an option for 'English and Arabic'

Yes, see it more as options for
- 'see everything' and
- 'see only english (because I don't understand arabic)'

The option for just arabic was not considered necessary

----

Also I think @SilkeLiwan will respond if you want to ask her something, if you raise an issue on the old repo

**Comment by JWLD** [comment]
Ok wicked, thanks
