### ISSUE TITLE
Inputs in add event form

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#67]
So I just need your guys's suggestion on what inputs we do not need in the add event form.
Since we are going to add more inputs for Arabic, filling up the form is going to talk ages with tedious.

So suggestions ?

**Comment by JWLD** [comment]
To be honest actually I'm not sure it needs changing much...

So it's only two fields for events (name and description) - we can easily add both of these so no need to remove anything from the events form.

There're four for places (name, description, address, opening hours). We can get rid of location for now like Lubes said, but I don't know if it's worth removing any others.

Also, I just noticed the categories dropdowns don't allow you to select multiple options - was this intentional?

**Comment by Karyum** [comment]
@JWLD are you sure cause i feel like location email website and the description of the place are not needed but that's my opinion.
and for the categories I don't know if it was intentional

**Comment by mattlub** [comment]
I would agree with @JWLD , for the events form I wouldn't remove anything. A few comments/suggestions though:
- rename 'place' label to 'location'
- rename 'title' to 'name'
- do not allow negative cost
- remove 'end date' (as most events start and end on same day)- maybe add a checkbox for 'event spans multiple days' and if checked, the end date field appears (this is open to discussion but I think currently it is a bit long)

maybe create another issue for the places fields?

**Comment by MohamedOmarii** [comment]
I think we have to do stand up for this issue
